#! /usr/bin/env ruby

require 'caitiff'

LawListener.with_current(judge = Judge.new) do
  ARGV.each {|file| require file}
end

judge.fallacies.each do |fallacy|
  puts "Fallacy: #{fallacy.law.filename}:#{fallacy.law.line_number}"
  fallacy.law.source.each do |source_line|
    puts "  #{source_line}"
  end
  puts "  ----"
  puts "  #{fallacy.details}" if fallacy.details
  if fallacy.error
    puts "  #{fallacy.error.inspect}"
    fallacy.error.backtrace.each do |backtrace_line|
      puts "  #{backtrace_line}"
    end
  end
  puts ""
end

puts judge.summary
