#! /usr/bin/env ruby

require 'caitiff'

LawListener.with_current(judge = Judge.new) do
  ARGV.each {|file| require file}
end

judge.fallacies.each do |fallacy|
  puts "Fallacy: #{fallacy.law.filename}:#{fallacy.law.line_number}"
  fallacy.law.source.each do |source_line|
    puts "  #{source_line}"
  end
  puts "  ----"
  puts "  #{fallacy.details}"
  puts ""
end

puts judge.summary
